"""Regenerate dzdk/tui/logo.py from docs/images/dzaleka-logo.png.

The logo is one colour on a transparent background, so it is drawn with
Unicode quadrant blocks: each character cell holds 2x2 pixels. Terminal cells
are about twice as tall as they are wide, so a square logo needs twice as many
columns as rows.

    uv run --with pillow scripts/make_logo.py
"""
from collections import Counter
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "images" / "dzaleka-logo.png"
TARGET = ROOT / "dzdk" / "tui" / "logo.py"

# Index = top-left, top-right, bottom-left, bottom-right bits (8, 4, 2, 1).
QUADRANTS = " ▗▖▄▝▐▞▟▘▚▌▙▀▜▛█"
SIZES = {"LOGO_SMALL": 5, "LOGO_MEDIUM": 8, "LOGO_LARGE": 14}  # rows


def is_ink(pixel) -> bool:
    """The logo is tan on white: count a pixel as ink if it is opaque and not near-white."""
    r, g, b, a = pixel
    return a > 110 and min(r, g, b) < 185


def render(image: Image.Image, rows: int) -> str:
    cols = rows * 2
    img = image.resize((cols * 2, rows * 2), Image.LANCZOS)
    lines = []
    for y in range(rows):
        line = ""
        for x in range(cols):
            bits = 0
            for weight, (dx, dy) in zip((8, 4, 2, 1), ((0, 0), (1, 0), (0, 1), (1, 1))):
                if is_ink(img.getpixel((x * 2 + dx, y * 2 + dy))):
                    bits |= weight
            line += QUADRANTS[bits]
        lines.append(line.rstrip())
    return "\n".join(lines)


def main() -> None:
    image = Image.open(SOURCE).convert("RGBA")
    ink = Image.new("L", image.size)
    ink.putdata([255 if is_ink(p) else 0 for p in image.get_flattened_data()])
    image = image.crop(ink.getbbox())
    pixels = [p[:3] for p in image.get_flattened_data() if is_ink(p)]
    color = "#%02X%02X%02X" % Counter(pixels).most_common(1)[0][0]
    parts = ['"""Dzaleka Online Services logo as quadrant-block text.',
             "", "Generated by scripts/make_logo.py; do not edit by hand.", '"""', "",
             f'LOGO_COLOR = "{color}"', ""]
    for name, rows in SIZES.items():
        parts.append(f"{name} = (")
        parts += [f"    {line!r} \"\\n\"" for line in render(image, rows).split("\n")[:-1]]
        parts.append(f"    {render(image, rows).split(chr(10))[-1]!r}")
        parts.append(")")
        parts.append("")
    TARGET.write_text("\n".join(parts))
    print(f"wrote {TARGET} (colour {color})")


if __name__ == "__main__":
    main()
